### ISSUE TITLE
Bug - os_upgrade.yml

### ISSUE THREAD

**Issue by reelsense** [stationgroup/ansible-experiments#7]
# 1

**First** run of `os_upgrade.yml` from _ubuntu1_ fails on FreeBSD.

```yml
TASK [include_role] ********************************************************************************

TASK [freebsd-update : Fetch any new FreeBSD updates] **********************************************
fatal: [freebsd6]: FAILED! => {"changed": true, "cmd": ["freebsd-update", "fetch", "--not-running-from-cron"], "delta": "0:00:01.855793", "end": "2018-05-14 16:25:03.876210", "msg": "non-zero return code", "rc": 1, "start": "2018-05-14 16:25:02.020417", "stderr": "rm: filelist: No such file or directory", "stderr_lines": ["rm: filelist: No such file or directory"], "stdout": "src component not installed, skipped\nLooking up update.FreeBSD.org mirrors... 3 mirrors found.\nFetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.\nFetching metadata index... done.\nInspecting system... done.\nPreparing to download files... done.", "stdout_lines": ["src component not installed, skipped", "Looking up update.FreeBSD.org mirrors... 3 mirrors found.", "Fetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.", "Fetching metadata index... done.", "Inspecting system... done.", "Preparing to download files... done."]}
changed: [freebsd5]

TASK [freebsd-update : debug] **********************************************************************
ok: [freebsd5] => {
    "result_update": {
        "changed": true,
        "cmd": [
            "freebsd-update",
            "fetch",
            "--not-running-from-cron"
        ],
        "delta": "0:00:02.422424",
        "end": "2018-05-14 16:25:04.370622",
        "failed": false,
        "rc": 0,
        "start": "2018-05-14 16:25:01.948198",
        "stderr": "rm: filelist: No such file or directory\nmv: tag.new: No such file or directory\ngrep: INDEX-OLD: No such file or directory\ngrep: INDEX-OLD: No such file or directory\ngrep: INDEX-OLD: No such file or directory\ngrep: INDEX-OLD: No such file or directory\ngrep: INDEX-OLD: No such file or directory\ncomm: INDEX-OLD: No such file or directory\nsort: No such file or directory",
        "stderr_lines": [
            "rm: filelist: No such file or directory",
            "mv: tag.new: No such file or directory",
            "grep: INDEX-OLD: No such file or directory",
            "grep: INDEX-OLD: No such file or directory",
            "grep: INDEX-OLD: No such file or directory",
            "grep: INDEX-OLD: No such file or directory",
            "grep: INDEX-OLD: No such file or directory",
            "comm: INDEX-OLD: No such file or directory",
            "sort: No such file or directory"
        ],
        "stdout": "src component not installed, skipped\nLooking up update.FreeBSD.org mirrors... 3 mirrors found.\nFetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.\nFetching metadata index... done.\nInspecting system... done.\nPreparing to download files... done.\n\nThe following files will be removed as part of updating to 11.1-RELEASE-p10:\n/bin/freebsd-version\n/bin/pgrep\n/bin/pkill\n/bin/ps\n/boot/kernel/aesni.ko\n/boot/kernel/agp.ko\n/boot/kernel/alq.ko\n/boot/kernel/aout.ko\n/boot/kernel/arcmsr.ko\n/boot/kernel/autofs.ko\n/boot/kernel/cam.ko\n/boot/kernel/cd9660.ko\n/boot/kernel/cloudabi.ko\n/boot/kernel/cloudabi32.ko\n/boot/kernel/cloudabi64.ko\n/boot/kernel/coretemp.ko\n/boot/kernel/cpuctl.ko\n/boot/kernel/cpufreq.ko\n/boot/kernel/crypto.ko\n/boot/kernel/ctl.ko\n/boot/kernel/cuse.ko\n/boot/kernel/cxgbei.ko\n/boot/kernel/drm.ko\n/boot/kernel/drm2.ko\n/boot/kernel/dtrace.ko\n/boot/kernel/efirt.ko\n/boot/kernel/ext2fs.ko\n/boot/kernel/fasttrap.ko\n/boot/kernel/fdescfs.ko\n/boot/kernel/filemon.ko\n/boot/kernel/firmware.ko\n/boot/kernel/fuse.ko\n/boot/kernel/geom_eli.ko\n/boot/kernel/geom_journal.ko\n/boot/kernel/geom_md.ko\n/boot/kernel/geom_mirror.ko\n/boot/kernel/geom_raid.ko\n/boot/kernel/geom_raid3.ko\n/boot/kernel/geom_sched.ko\n/boot/kernel/geom_uzip.ko\n/boot/kernel/hpt27xx.ko\n/boot/kernel/hptmv.ko\n/boot/kernel/hptnr.ko\n/boot/kernel/hptrr.ko\n/boot/kernel/hv_utils.ko\n/boot/kernel/hv_vmbus.ko\n/boot/kernel/hwpmc.ko\n/boot/kernel/i915.ko\n/boot/kernel/i915kms.ko\n/boot/kernel/if_an.ko\n/boot/kernel/if_ath.ko\n/boot/kernel/if_aue.ko\n/boot/kernel/if_axe.ko\n/boot/kernel/if_axge.ko\n/boot/kernel/if_bnxt.ko\n/boot/kernel/if_bridge.ko\n/boot/kernel/if_cas.ko\n/boot/kernel/if_ena.ko\n/boot/kernel/if_gif.ko\n/boot/kernel/if_gre.ko\n/boot/kernel/if_iwi.ko\n/boot/kernel/if_ix.ko\n/boot/kernel/if_ixl.ko\n/boot/kernel/if_ixlv.ko\n/boot/kernel/if_ixv.ko\n/boot/kernel/if_lagg.ko\n/boot/kernel/if_lmc.ko\n/boot/kernel/if_me.ko\n/boot/kernel/if_mos.ko\n/boot/kernel/if_ndis.ko\n/boot/kernel/if_nxge.ko\n/boot/kernel/if_qlnxe.ko\n/boot/kernel/if_rue.ko\n/boot/kernel/if_run.ko\n/boot/kernel/if_smsc.ko",
        "stdout_lines": [
            "src component not installed, skipped",
            "Looking up update.FreeBSD.org mirrors... 3 mirrors found.",
            "Fetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.",
            "Fetching metadata index... done.",
            "Inspecting system... done.",
            "Preparing to download files... done.",
            "",
            "The following files will be removed as part of updating to 11.1-RELEASE-p10:",
            "/bin/freebsd-version",
            "/bin/pgrep",
            "/bin/pkill",
            "/bin/ps",
            "/boot/kernel/aesni.ko",
            "/boot/kernel/agp.ko",
            "/boot/kernel/alq.ko",
            "/boot/kernel/aout.ko",
            "/boot/kernel/arcmsr.ko",
            "/boot/kernel/autofs.ko",
            "/boot/kernel/cam.ko",
            "/boot/kernel/cd9660.ko",
            "/boot/kernel/cloudabi.ko",
            "/boot/kernel/cloudabi32.ko",
            "/boot/kernel/cloudabi64.ko",
            "/boot/kernel/coretemp.ko",
            "/boot/kernel/cpuctl.ko",
            "/boot/kernel/cpufreq.ko",
            "/boot/kernel/crypto.ko",
            "/boot/kernel/ctl.ko",
            "/boot/kernel/cuse.ko",
            "/boot/kernel/cxgbei.ko",
            "/boot/kernel/drm.ko",
            "/boot/kernel/drm2.ko",
            "/boot/kernel/dtrace.ko",
            "/boot/kernel/efirt.ko",
            "/boot/kernel/ext2fs.ko",
            "/boot/kernel/fasttrap.ko",
            "/boot/kernel/fdescfs.ko",
            "/boot/kernel/filemon.ko",
            "/boot/kernel/firmware.ko",
            "/boot/kernel/fuse.ko",
            "/boot/kernel/geom_eli.ko",
            "/boot/kernel/geom_journal.ko",
            "/boot/kernel/geom_md.ko",
            "/boot/kernel/geom_mirror.ko",
            "/boot/kernel/geom_raid.ko",
            "/boot/kernel/geom_raid3.ko",
            "/boot/kernel/geom_sched.ko",
            "/boot/kernel/geom_uzip.ko",
            "/boot/kernel/hpt27xx.ko",
            "/boot/kernel/hptmv.ko",
            "/boot/kernel/hptnr.ko",
            "/boot/kernel/hptrr.ko",
            "/boot/kernel/hv_utils.ko",
            "/boot/kernel/hv_vmbus.ko",
            "/boot/kernel/hwpmc.ko",
            "/boot/kernel/i915.ko",
            "/boot/kernel/i915kms.ko",
            "/boot/kernel/if_an.ko",
            "/boot/kernel/if_ath.ko",
            "/boot/kernel/if_aue.ko",
            "/boot/kernel/if_axe.ko",
            "/boot/kernel/if_axge.ko",
            "/boot/kernel/if_bnxt.ko",
            "/boot/kernel/if_bridge.ko",
            "/boot/kernel/if_cas.ko",
            "/boot/kernel/if_ena.ko",
            "/boot/kernel/if_gif.ko",
            "/boot/kernel/if_gre.ko",
            "/boot/kernel/if_iwi.ko",
            "/boot/kernel/if_ix.ko",
            "/boot/kernel/if_ixl.ko",
            "/boot/kernel/if_ixlv.ko",
            "/boot/kernel/if_ixv.ko",
            "/boot/kernel/if_lagg.ko",
            "/boot/kernel/if_lmc.ko",
            "/boot/kernel/if_me.ko",
            "/boot/kernel/if_mos.ko",
            "/boot/kernel/if_ndis.ko",
            "/boot/kernel/if_nxge.ko",
            "/boot/kernel/if_qlnxe.ko",
            "/boot/kernel/if_rue.ko",
            "/boot/kernel/if_run.ko",
            "/boot/kernel/if_smsc.ko"
        ]
    }
}

TASK [freebsd-update : Install FreeBSD updates] ****************************************************
changed: [freebsd5]

TASK [freebsd-update : debug] **********************************************************************
ok: [freebsd5] => {
    "result_update_install": {
        "changed": true,
        "cmd": [
            "freebsd-update",
            "install",
            "--not-running-from-cron"
        ],
        "delta": "0:00:01.585784",
        "end": "2018-05-14 16:25:06.249316",
        "failed": false,
        "rc": 0,
        "start": "2018-05-14 16:25:04.663532",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "src component not installed, skipped\nInstalling updates... done.",
        "stdout_lines": [
            "src component not installed, skipped",
            "Installing updates... done."
        ]
    }
}

TASK [freebsd-update : Upgrade FreeBSD packages - dry-run] *****************************************
skipping: [freebsd5]

TASK [freebsd-update : Upgrade FreeBSD packages] ***************************************************
changed: [freebsd5]

TASK [freebsd-update : debug] **********************************************************************
ok: [freebsd5] => {
    "result_pkg": {
        "changed": true,
        "cmd": [
            "pkg",
            "upgrade",
            "--yes"
        ],
        "delta": "0:00:02.003878",
        "end": "2018-05-14 16:25:08.600126",
        "failed": false,
        "rc": 0,
        "start": "2018-05-14 16:25:06.596248",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "Updating FreeBSD repository catalogue...\nFreeBSD repository is up to date.\nAll repositories are up to date.\nChecking for upgrades (4 candidates): .... done\nProcessing candidates (4 candidates): .... done\nThe following 3 package(s) will be affected (of 0 checked):\n\nInstalled packages to be UPGRADED:\n\tlibxml2: 2.9.4 -> 2.9.7\n\texpat: 2.2.1 -> 2.2.5\n\nInstalled packages to be REINSTALLED:\n\tlibpthread-stubs-0.4 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:11:*')\n\nNumber of packages to be upgraded: 2\nNumber of packages to be reinstalled: 1\n\n938 KiB to be downloaded.\n[1/3] Fetching libxml2-2.9.7.txz: .......... done\n[2/3] Fetching libpthread-stubs-0.4.txz: . done\n[3/3] Fetching expat-2.2.5.txz: .......... done\nChecking integrity... done (0 conflicting)\n[1/3] Upgrading libxml2 from 2.9.4 to 2.9.7...\n[1/3] Extracting libxml2-2.9.7: .......... done\n[2/3] Reinstalling libpthread-stubs-0.4...\n[2/3] Extracting libpthread-stubs-0.4: .... done\n[3/3] Upgrading expat from 2.2.1 to 2.2.5...\n[3/3] Extracting expat-2.2.5: .......... done",
        "stdout_lines": [
            "Updating FreeBSD repository catalogue...",
            "FreeBSD repository is up to date.",
            "All repositories are up to date.",
            "Checking for upgrades (4 candidates): .... done",
            "Processing candidates (4 candidates): .... done",
            "The following 3 package(s) will be affected (of 0 checked):",
            "",
            "Installed packages to be UPGRADED:",
            "\tlibxml2: 2.9.4 -> 2.9.7",
            "\texpat: 2.2.1 -> 2.2.5",
            "",
            "Installed packages to be REINSTALLED:",
            "\tlibpthread-stubs-0.4 (ABI changed: 'freebsd:11:x86:64' -> 'freebsd:11:*')",
            "",
            "Number of packages to be upgraded: 2",
            "Number of packages to be reinstalled: 1",
            "",
            "938 KiB to be downloaded.",
            "[1/3] Fetching libxml2-2.9.7.txz: .......... done",
            "[2/3] Fetching libpthread-stubs-0.4.txz: . done",
            "[3/3] Fetching expat-2.2.5.txz: .......... done",
            "Checking integrity... done (0 conflicting)",
            "[1/3] Upgrading libxml2 from 2.9.4 to 2.9.7...",
            "[1/3] Extracting libxml2-2.9.7: .......... done",
            "[2/3] Reinstalling libpthread-stubs-0.4...",
            "[2/3] Extracting libpthread-stubs-0.4: .... done",
            "[3/3] Upgrading expat from 2.2.1 to 2.2.5...",
            "[3/3] Extracting expat-2.2.5: .......... done"
        ]
    }
}

PLAY RECAP *****************************************************************************************
freebsd5                   : ok=8    changed=3    unreachable=0    failed=0   
freebsd6                   : ok=2    changed=0    unreachable=0    failed=1   
ubuntu1                    : ok=2    changed=0    unreachable=0    failed=0   
ubuntu2                    : ok=2    changed=0    unreachable=0    failed=0   
ubuntu3                    : ok=2    changed=0    unreachable=0    failed=0   
ubuntu4                    : ok=2    changed=0    unreachable=0    failed=0   
```

---

# 2

**Second** run of `os_upgrade.yml` from _ubuntu1_ fails on FreeBSD.

```yml
PLAY [upgrade debian based machines] ***************************************************************

TASK [include_role] ********************************************************************************
skipping: [freebsd5]
skipping: [freebsd6]
ERROR! the role 'debian-update' was not found in /home/vagrant/ansible-experiments/package_updates/roles:/home/vagrant/ansible-experiments/package_updates/roles:/home/vagrant/ansible-experiments/package_updates

The error appears to have been in '/home/vagrant/ansible-experiments/package_updates/os_upgrade.yml': line 14, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - include_role:
        name: debian-update
              ^ here


TASK [include_role] ********************************************************************************

TASK [freebsd-update : Fetch any new FreeBSD updates] **********************************************
fatal: [freebsd5]: FAILED! => {"changed": true, "cmd": ["freebsd-update", "fetch", "--not-running-from-cron"], "delta": "0:00:00.761538", "end": "2018-05-14 16:27:13.249229", "msg": "non-zero return code", "rc": 1, "start": "2018-05-14 16:27:12.487691", "stderr": "rm: latest.ssl: No such file or directory\ngrep: sanitycheck.tmp: No such file or directory\ngrep: sanitycheck.tmp: No such file or directory\ngrep: sanitycheck.tmp: No such file or directory\nrm: sanitycheck.tmp: No such file or directory", "stderr_lines": ["rm: latest.ssl: No such file or directory", "grep: sanitycheck.tmp: No such file or directory", "grep: sanitycheck.tmp: No such file or directory", "grep: sanitycheck.tmp: No such file or directory", "rm: sanitycheck.tmp: No such file or directory"], "stdout": "src component not installed, skipped\nLooking up update.FreeBSD.org mirrors... 3 mirrors found.\nFetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.\nFetching metadata index... done.", "stdout_lines": ["src component not installed, skipped", "Looking up update.FreeBSD.org mirrors... 3 mirrors found.", "Fetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.", "Fetching metadata index... done."]}
ok: [freebsd6]

TASK [freebsd-update : debug] **********************************************************************
skipping: [freebsd6]

TASK [freebsd-update : Install FreeBSD updates] ****************************************************
skipping: [freebsd6]

TASK [freebsd-update : debug] **********************************************************************
skipping: [freebsd6]

TASK [freebsd-update : Upgrade FreeBSD packages - dry-run] *****************************************
skipping: [freebsd6]

TASK [freebsd-update : Upgrade FreeBSD packages] ***************************************************
ok: [freebsd6]

TASK [freebsd-update : debug] **********************************************************************
skipping: [freebsd6]

PLAY RECAP *****************************************************************************************
freebsd5                   : ok=2    changed=0    unreachable=0    failed=1   
freebsd6                   : ok=4    changed=0    unreachable=0    failed=0   
ubuntu1                    : ok=2    changed=0    unreachable=0    failed=0   
ubuntu2                    : ok=2    changed=0    unreachable=0    failed=0   
ubuntu3                    : ok=2    changed=0    unreachable=0    failed=0   
ubuntu4                    : ok=2    changed=0    unreachable=0    failed=0   

```

---
x-post: https://github.com/stationgroup/ansible-experiments/issues/7
https://github.com/stationgroup/ansible-experiments/issues/6
